# Generated by Django 4.2.4 on 2023-09-05 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitterstats',
            name='futurevalue',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(80)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hitterstats',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
