# Generated by Django 4.2.4 on 2023-09-07 01:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_hitterstats_futurevalue_alter_hitterstats_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitcherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('team', models.IntegerField()),
                ('position', models.CharField(max_length=3)),
                ('throws', models.CharField(max_length=1)),
                ('date', models.DateField()),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PitcherStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_type', models.CharField(max_length=15)),
                ('velo_low', models.IntegerField()),
                ('velo_high', models.IntegerField()),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(80)])),
                ('futurevalue', models.IntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(80)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pitcherreport')),
            ],
        ),
    ]
