# Generated by Django 4.2.4 on 2023-09-07 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_pitcherreport_pitcherstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitcherreport',
            name='fvoverall',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(80)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pitcherreport',
            name='overall',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(80)]),
            preserve_default=False,
        ),
    ]
