# Generated by Django 4.2.4 on 2023-09-11 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_pitcherreport_fvoverall_pitcherreport_overall'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitterreport',
            name='fvoverall',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(80)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hitterreport',
            name='overall',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(80)]),
            preserve_default=False,
        ),
    ]
